[package]
name = "wh40k_boarding_rules"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
wh40k_core_types = { workspace = true }
wh40k_boarding_content = { workspace = true }
wh40k_geometry = { workspace = true }

[dev-dependencies]
wh40k_boarding_content = { workspace = true }
