[package]
name = "wh40k_selfplay"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
wh40k_core_types = { workspace = true }
wh40k_game_core = { workspace = true }
wh40k_search_core = { workspace = true }
wh40k_replay = { workspace = true }
wh40k_dice = { workspace = true }
