//! Weapon ability enums and weapon profile types.
//!
//! Source: 40k_revised.md - "WEAPON ABILITIES" section
//! Source: Custodes.md, Frenzied_Reavers.md - Weapon profiles

use serde::{Deserialize, Serialize};
use crate::keywords::Keyword;

/// Individual weapon ability that modifies attack behavior.
/// Source: 40k_revised.md - Weapon Abilities
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WeaponAbility {
    /// Can shoot after Advancing (normally can't). Hit roll modified by -1.
    /// Source: 40k_revised.md - "ASSAULT"
    Assault,

    /// +1 to Hit rolls if bearer didn't move (Remain Stationary).
    /// Source: 40k_revised.md - "HEAVY"
    Heavy,

    /// +N attacks when within half range.
    /// Source: 40k_revised.md - "RAPID FIRE"
    RapidFire(u8),

    /// Can be used in Engagement Range. Shoots only at units in ER or own unit.
    /// Source: 40k_revised.md - "PISTOL"
    Pistol,

    /// +1 Attack per 5 models in target unit.
    /// Cannot target units within Engagement Range of friendly units.
    /// Source: 40k_revised.md - "BLAST"
    Blast,

    /// Automatically hits (no Hit roll).
    /// Source: 40k_revised.md - "TORRENT"
    Torrent,

    /// Re-roll failed Wound rolls.
    /// Source: 40k_revised.md - "TWIN-LINKED"
    TwinLinked,

    /// Critical Hit (unmodified 6) auto-wounds (skip Wound roll).
    /// Source: 40k_revised.md - "LETHAL HITS"
    LethalHits,

    /// Critical Hit generates N extra hits.
    /// Source: 40k_revised.md - "SUSTAINED HITS"
    SustainedHits(u8),

    /// Critical Wound deals mortal wounds instead of normal damage.
    /// Source: 40k_revised.md - "DEVASTATING WOUNDS"
    DevastatingWounds,

    /// After attacking, roll D6 for each model with Hazardous weapon.
    /// On 1, bearer suffers 3 mortal wounds (1 if not CHARACTER/MONSTER/VEHICLE).
    /// Source: 40k_revised.md - "HAZARDOUS"
    Hazardous,

    /// Can target CHARACTERs in Attached units directly.
    /// Source: 40k_revised.md - "PRECISION"
    Precision,

    /// Critical Wound on 4+/5+/6+ when targeting units with specified keyword.
    /// Anti(keyword, threshold) - e.g., Anti(Infantry, 4) = Anti-INFANTRY 4+
    /// Source: 40k_revised.md - "ANTI-"
    Anti(Keyword, u8),

    /// Can target non-visible units. -1 to Hit, +1 to enemy save (Cover benefit).
    /// Source: 40k_revised.md - "INDIRECT FIRE"
    IndirectFire,

    /// Target cannot benefit from cover.
    /// Source: 40k_revised.md - "IGNORES COVER"
    IgnoresCover,

    /// +N to Damage when within half range.
    /// Source: 40k_revised.md - "MELTA"
    Melta(u8),

    /// +1 to Wound roll if bearer Charged this turn.
    /// Source: 40k_revised.md - "LANCE"
    Lance,

    /// Extra attacks generated by this weapon don't prevent attacking with other weapons.
    /// Source: 40k_revised.md - "EXTRA ATTACKS"
    ExtraAttacks,
}

/// Set of weapon abilities for a weapon profile.
/// Uses a Vec since weapon abilities can have parameters (unlike keywords which
/// are simple on/off flags well-suited to bitflags).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
pub struct WeaponAbilitySet {
    pub abilities: Vec<WeaponAbility>,
}

impl WeaponAbilitySet {
    pub fn new() -> Self {
        Self {
            abilities: Vec::new(),
        }
    }

    pub fn from_abilities(abilities: Vec<WeaponAbility>) -> Self {
        Self { abilities }
    }

    pub fn add(&mut self, ability: WeaponAbility) {
        if !self.abilities.contains(&ability) {
            self.abilities.push(ability);
        }
    }

    pub fn has(&self, ability: &WeaponAbility) -> bool {
        self.abilities.contains(ability)
    }

    /// Check if the weapon has any variant of a specific ability type.
    pub fn has_assault(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::Assault))
    }

    pub fn has_heavy(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::Heavy))
    }

    pub fn has_pistol(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::Pistol))
    }

    pub fn has_blast(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::Blast))
    }

    pub fn has_torrent(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::Torrent))
    }

    pub fn has_twin_linked(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::TwinLinked))
    }

    pub fn has_lethal_hits(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::LethalHits))
    }

    pub fn has_devastating_wounds(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::DevastatingWounds))
    }

    pub fn has_hazardous(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::Hazardous))
    }

    pub fn has_precision(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::Precision))
    }

    pub fn has_indirect_fire(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::IndirectFire))
    }

    pub fn has_ignores_cover(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::IgnoresCover))
    }

    pub fn has_lance(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::Lance))
    }

    pub fn has_extra_attacks(&self) -> bool {
        self.abilities.iter().any(|a| matches!(a, WeaponAbility::ExtraAttacks))
    }

    /// Get the Sustained Hits value if present.
    pub fn sustained_hits_value(&self) -> Option<u8> {
        self.abilities.iter().find_map(|a| {
            if let WeaponAbility::SustainedHits(n) = a {
                Some(*n)
            } else {
                None
            }
        })
    }

    /// Get the total Sustained Hits value (can stack from multiple sources).
    pub fn total_sustained_hits(&self) -> u8 {
        self.abilities
            .iter()
            .filter_map(|a| {
                if let WeaponAbility::SustainedHits(n) = a {
                    Some(*n)
                } else {
                    None
                }
            })
            .sum()
    }

    /// Get the Rapid Fire value if present.
    pub fn rapid_fire_value(&self) -> Option<u8> {
        self.abilities.iter().find_map(|a| {
            if let WeaponAbility::RapidFire(n) = a {
                Some(*n)
            } else {
                None
            }
        })
    }

    /// Get the Melta bonus damage if present.
    pub fn melta_value(&self) -> Option<u8> {
        self.abilities.iter().find_map(|a| {
            if let WeaponAbility::Melta(n) = a {
                Some(*n)
            } else {
                None
            }
        })
    }

    /// Get all Anti- abilities.
    pub fn anti_abilities(&self) -> Vec<(Keyword, u8)> {
        self.abilities
            .iter()
            .filter_map(|a| {
                if let WeaponAbility::Anti(kw, threshold) = a {
                    Some((*kw, *threshold))
                } else {
                    None
                }
            })
            .collect()
    }

    /// Check if Anti- ability applies against a target with given keyword.
    pub fn anti_threshold_for(&self, keyword: Keyword) -> Option<u8> {
        self.abilities.iter().find_map(|a| {
            if let WeaponAbility::Anti(kw, threshold) = a {
                if *kw == keyword {
                    Some(*threshold)
                } else {
                    None
                }
            } else {
                None
            }
        })
    }
}

/// Whether a weapon is ranged or melee.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WeaponType {
    Ranged,
    Melee,
}

/// A complete weapon profile.
/// Source: 40k_revised.md - Weapon characteristics
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WeaponProfile {
    /// Unique identifier for this weapon profile
    pub id: crate::WeaponId,
    /// Display name
    pub name: String,
    /// Ranged or Melee
    pub weapon_type: WeaponType,
    /// Range in inches (Melee = 0)
    pub range: crate::Inches,
    /// Number of attacks
    pub attacks: crate::AttackCount,
    /// Ballistic Skill (ranged) or Weapon Skill (melee)
    pub skill: crate::Skill,
    /// Strength
    pub strength: crate::Strength,
    /// Armor Penetration
    pub ap: crate::ArmorPenetration,
    /// Damage
    pub damage: crate::Damage,
    /// Weapon abilities
    pub abilities: WeaponAbilitySet,
}

impl WeaponProfile {
    /// Whether this weapon can be fired after Advancing
    pub fn can_fire_after_advance(&self) -> bool {
        self.abilities.has_assault() || self.abilities.has_pistol()
    }

    /// Whether this weapon can be used in Engagement Range
    pub fn can_fire_in_engagement(&self) -> bool {
        self.abilities.has_pistol() || self.weapon_type == WeaponType::Melee
    }

    /// Whether this weapon auto-hits (Torrent)
    pub fn auto_hits(&self) -> bool {
        self.abilities.has_torrent()
    }

    /// Whether hit rolls get +1 for remaining stationary (Heavy)
    pub fn benefits_from_stationary(&self) -> bool {
        self.abilities.has_heavy()
    }

    /// Half range for Rapid Fire and Melta bonuses
    pub fn half_range(&self) -> crate::Inches {
        crate::Inches(self.range.0 / 2)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::*;

    #[test]
    fn test_weapon_ability_set() {
        let mut abilities = WeaponAbilitySet::new();
        abilities.add(WeaponAbility::Assault);
        abilities.add(WeaponAbility::Pistol);
        assert!(abilities.has_assault());
        assert!(abilities.has_pistol());
        assert!(!abilities.has_blast());
    }

    #[test]
    fn test_weapon_ability_set_no_duplicates() {
        let mut abilities = WeaponAbilitySet::new();
        abilities.add(WeaponAbility::Assault);
        abilities.add(WeaponAbility::Assault);
        assert_eq!(abilities.abilities.len(), 1);
    }

    #[test]
    fn test_sustained_hits() {
        let abilities = WeaponAbilitySet::from_abilities(vec![
            WeaponAbility::SustainedHits(1),
        ]);
        assert_eq!(abilities.sustained_hits_value(), Some(1));
        assert_eq!(abilities.total_sustained_hits(), 1);
    }

    #[test]
    fn test_sustained_hits_stacking() {
        // Dacatarai + Hurricanus = Sustained Hits 2
        let abilities = WeaponAbilitySet::from_abilities(vec![
            WeaponAbility::SustainedHits(1), // Hurricanus native
            WeaponAbility::SustainedHits(1), // Dacatarai stance
        ]);
        assert_eq!(abilities.total_sustained_hits(), 2);
    }

    #[test]
    fn test_anti_abilities() {
        let abilities = WeaponAbilitySet::from_abilities(vec![
            WeaponAbility::Anti(Keyword::Infantry, 4),
        ]);
        assert_eq!(
            abilities.anti_threshold_for(Keyword::Infantry),
            Some(4)
        );
        assert_eq!(abilities.anti_threshold_for(Keyword::Monster), None);
    }

    #[test]
    fn test_rapid_fire() {
        let abilities = WeaponAbilitySet::from_abilities(vec![
            WeaponAbility::RapidFire(1),
        ]);
        assert_eq!(abilities.rapid_fire_value(), Some(1));
    }

    #[test]
    fn test_melta() {
        let abilities = WeaponAbilitySet::from_abilities(vec![
            WeaponAbility::Melta(2),
        ]);
        assert_eq!(abilities.melta_value(), Some(2));
    }

    #[test]
    fn test_weapon_profile_sentinel_blade_ranged() {
        // Custodian Guard - Sentinel Blade (ranged profile)
        // Source: Custodes.md - Custodian Guard datasheets
        let weapon = WeaponProfile {
            id: WeaponId::new(1),
            name: "Sentinel blade".to_string(),
            weapon_type: WeaponType::Ranged,
            range: Inches::from_inches(12),
            attacks: AttackCount::Fixed(2),
            skill: Skill::TWO_PLUS,
            strength: Strength::new(4),
            ap: ArmorPenetration::MINUS_1,
            damage: Damage::Fixed(2),
            abilities: WeaponAbilitySet::from_abilities(vec![
                WeaponAbility::Assault,
                WeaponAbility::Pistol,
            ]),
        };
        assert!(weapon.can_fire_after_advance());
        assert!(weapon.can_fire_in_engagement());
        assert_eq!(weapon.half_range(), Inches::from_inches(6));
    }

    #[test]
    fn test_weapon_profile_hellforged_weapons() {
        // Vorrakh - Hellforged weapons
        // Source: Frenzied_Reavers.md - Vorrakh datasheet
        let weapon = WeaponProfile {
            id: WeaponId::new(2),
            name: "Hellforged weapons".to_string(),
            weapon_type: WeaponType::Melee,
            range: Inches::ZERO,
            attacks: AttackCount::Fixed(16),
            skill: Skill::TWO_PLUS,
            strength: Strength::new(6),
            ap: ArmorPenetration::MINUS_1,
            damage: Damage::Fixed(1),
            abilities: WeaponAbilitySet::new(),
        };
        assert!(!weapon.can_fire_after_advance());
        assert!(weapon.can_fire_in_engagement());
        assert!(!weapon.auto_hits());
    }

    #[test]
    fn test_weapon_profile_axe_of_dismemberment() {
        // Master of Executions - Axe of dismemberment
        // Source: Frenzied_Reavers.md - MoE datasheet
        let weapon = WeaponProfile {
            id: WeaponId::new(3),
            name: "Axe of dismemberment".to_string(),
            weapon_type: WeaponType::Melee,
            range: Inches::ZERO,
            attacks: AttackCount::Fixed(5),
            skill: Skill::TWO_PLUS,
            strength: Strength::new(7),
            ap: ArmorPenetration::MINUS_2,
            damage: Damage::Fixed(2),
            abilities: WeaponAbilitySet::from_abilities(vec![
                WeaponAbility::DevastatingWounds,
                WeaponAbility::Precision,
            ]),
        };
        assert!(weapon.abilities.has_devastating_wounds());
        assert!(weapon.abilities.has_precision());
    }

    #[test]
    fn test_weapon_profile_serialization() {
        let weapon = WeaponProfile {
            id: WeaponId::new(1),
            name: "Test weapon".to_string(),
            weapon_type: WeaponType::Ranged,
            range: Inches::from_inches(24),
            attacks: AttackCount::Fixed(2),
            skill: Skill::THREE_PLUS,
            strength: Strength::new(4),
            ap: ArmorPenetration::MINUS_1,
            damage: Damage::Fixed(1),
            abilities: WeaponAbilitySet::from_abilities(vec![WeaponAbility::Assault]),
        };
        let json = serde_json::to_string(&weapon).unwrap();
        let back: WeaponProfile = serde_json::from_str(&json).unwrap();
        assert_eq!(weapon, back);
    }

    #[test]
    fn test_weapon_profile_balistus_grenade_launcher() {
        // Allarus Custodians - Balistus grenade launcher
        // Source: Custodes.md - Allarus datasheet
        let weapon = WeaponProfile {
            id: WeaponId::new(4),
            name: "Balistus grenade launcher".to_string(),
            weapon_type: WeaponType::Ranged,
            range: Inches::from_inches(18),
            attacks: AttackCount::D6,
            skill: Skill::TWO_PLUS,
            strength: Strength::new(4),
            ap: ArmorPenetration::MINUS_1,
            damage: Damage::Fixed(1),
            abilities: WeaponAbilitySet::from_abilities(vec![WeaponAbility::Blast]),
        };
        assert!(weapon.abilities.has_blast());
        assert_eq!(weapon.attacks.min_value(), 1);
        assert_eq!(weapon.attacks.max_value(), 6);
    }

    #[test]
    fn test_weapon_profile_plasma_pistol() {
        // Berzerkers - Plasma pistol (supercharge)
        // Source: Frenzied_Reavers.md - Berzerkers datasheet
        let weapon = WeaponProfile {
            id: WeaponId::new(5),
            name: "Plasma pistol - supercharge".to_string(),
            weapon_type: WeaponType::Ranged,
            range: Inches::from_inches(12),
            attacks: AttackCount::Fixed(1),
            skill: Skill::FOUR_PLUS,
            strength: Strength::new(8),
            ap: ArmorPenetration::MINUS_3,
            damage: Damage::Fixed(2),
            abilities: WeaponAbilitySet::from_abilities(vec![
                WeaponAbility::Hazardous,
                WeaponAbility::Pistol,
            ]),
        };
        assert!(weapon.abilities.has_hazardous());
        assert!(weapon.abilities.has_pistol());
        assert!(weapon.can_fire_in_engagement());
    }
}
