//! Phase state machine and progression.
//!
//! Manages the flow through phases, turns, and battle rounds.
//! Handles automatic actions at phase boundaries (CP gain, battle-shock tests).
//!
//! Source: implementation_v3.md Section 6.6 (Rules runtime)
//! Source: 40k_revised.md - Turn structure, Command Phase, Battle-shock
//! Source: CP_Rules.md - Combat Patrol phase structure

use wh40k_core_types::{
    BattleRound, BattleShockResult, GameOutcome, Phase, SubPhase,
};
use wh40k_event_system::GameEvent;

use crate::effect;
use crate::state::GameState;

// ---------------------------------------------------------------------------
// PhaseStateMachine
// ---------------------------------------------------------------------------

/// The phase state machine manages phase, turn, and round transitions.
///
/// It provides methods to advance the game through its phases,
/// handle automatic phase-start actions (CP gain, battle-shock),
/// and check for game-end conditions.
pub struct PhaseStateMachine;

impl PhaseStateMachine {
    /// Advance to the next phase/subphase/turn/round.
    ///
    /// Returns the events generated by the transition.
    pub fn advance_phase(state: &mut GameState) -> Vec<GameEvent> {
        let mut events = Vec::new();

        match state.current_phase {
            Phase::PreBattle => {
                // Transition from PreBattle to Command phase of round 1
                state.current_phase = Phase::Command;
                state.current_subphase = SubPhase::CommandPhaseStart;
                state.battle_round = BattleRound::new(1);

                events.push(GameEvent::BattleRoundStarted {
                    round: state.battle_round,
                });
                events.push(GameEvent::TurnStarted {
                    player: state.active_player,
                    round: state.battle_round,
                });
                events.push(GameEvent::PhaseStarted {
                    phase: Phase::Command,
                    player: state.active_player,
                });
            }
            Phase::Command => {
                events.extend(Self::end_current_phase(state, Phase::Command));
                state.current_phase = Phase::Movement;
                state.current_subphase = SubPhase::MovementPhaseStart;
                events.push(GameEvent::PhaseStarted {
                    phase: Phase::Movement,
                    player: state.active_player,
                });
            }
            Phase::Movement => {
                events.extend(Self::end_current_phase(state, Phase::Movement));
                state.current_phase = Phase::Shooting;
                state.current_subphase = SubPhase::ShootingPhaseStart;
                events.push(GameEvent::PhaseStarted {
                    phase: Phase::Shooting,
                    player: state.active_player,
                });
            }
            Phase::Shooting => {
                events.extend(Self::end_current_phase(state, Phase::Shooting));
                state.current_phase = Phase::Charge;
                state.current_subphase = SubPhase::ChargePhaseStart;
                events.push(GameEvent::PhaseStarted {
                    phase: Phase::Charge,
                    player: state.active_player,
                });
            }
            Phase::Charge => {
                events.extend(Self::end_current_phase(state, Phase::Charge));
                state.current_phase = Phase::Fight;
                state.current_subphase = SubPhase::FightPhaseStart;
                events.push(GameEvent::PhaseStarted {
                    phase: Phase::Fight,
                    player: state.active_player,
                });
            }
            Phase::Fight => {
                events.extend(Self::end_current_phase(state, Phase::Fight));
                events.extend(Self::end_player_turn(state));
            }
            Phase::GameEnd => {
                // Already ended, nothing to do
            }
        }

        // Tick effects after phase transition
        effect::tick_effects(
            &mut state.active_effects,
            state.battle_round,
            state.current_phase,
        );

        events
    }

    /// End the current phase and emit the PhaseEnded event.
    fn end_current_phase(state: &mut GameState, phase: Phase) -> Vec<GameEvent> {
        let events = vec![GameEvent::PhaseEnded {
            phase,
            player: state.active_player,
        }];

        // Clear phase-level stratagem tracking
        state.turn_flags.clear_phase_flags();
        state.player_mut(state.active_player).stratagem_usage.clear_phase();

        events
    }

    /// Start the Command Phase for the active player.
    ///
    /// 1. Gain 1 CP (unless first turn of the game for the player going first,
    ///    per CP_Rules - actually in 10th ed Combat Patrol, both players gain 1CP
    ///    each Command Phase starting from their first turn).
    /// 2. Check battle-shock for below-half-strength units.
    ///
    /// Source: 40k_revised.md - Command Phase
    /// Source: CP_Rules.md - "1CP gained each Command Phase"
    pub fn start_command_phase(state: &mut GameState) -> Vec<GameEvent> {
        let mut events = Vec::new();
        let player = state.active_player;

        // Gain 1 CP
        state.player_mut(player).gain_cp(1);
        events.push(GameEvent::CommandPointsGained {
            player,
            amount: 1,
            reason: wh40k_event_system::CpReason::CommandPhaseGain,
        });

        state.current_subphase = SubPhase::BattleShockTests;

        // Identify units that need battle-shock tests (below half strength)
        let units_needing_test: Vec<_> = state
            .units
            .iter()
            .filter(|u| {
                u.owner == player
                    && u.is_on_battlefield()
                    && !u.is_destroyed()
                    && u.is_below_half_strength()
            })
            .map(|u| u.id)
            .collect();

        for unit_id in &units_needing_test {
            events.push(GameEvent::BattleShockTestRequired { unit: *unit_id });
        }

        events
    }

    /// Process a battle-shock test for a unit.
    ///
    /// Roll 2D6 against the unit's Leadership. If the roll is greater than
    /// the Leadership value, the unit is battle-shocked.
    ///
    /// Source: 40k_revised.md - "Battle-shock"
    pub fn process_battle_shock(
        state: &mut GameState,
        unit_id: wh40k_core_types::UnitId,
    ) -> Vec<GameEvent> {
        let mut events = Vec::new();

        // Roll 2D6 for battle-shock test
        let roll = state.dice_roller.roll_2d6(
            wh40k_dice::RollPurpose::BattleShockTest {
                unit_id: unit_id.raw(),
            },
        );
        let roll_total = roll.0;

        let leadership = {
            let unit = match state.unit(unit_id) {
                Some(u) => u,
                None => return events,
            };
            unit.base_leadership.value()
        };

        // 40k_revised.md §4.2: roll ≥ Ld = passed, roll < Ld = failed
        let passed = roll_total >= leadership;
        let result = if passed {
            BattleShockResult::Passed
        } else {
            BattleShockResult::Failed
        };

        // Apply the result
        if let Some(unit) = state.unit_mut(unit_id) {
            unit.battle_shocked = !passed;
        }

        events.push(GameEvent::BattleShockTestResolved {
            unit: unit_id,
            result,
            roll: roll_total,
        });

        events
    }

    /// Start the Movement Phase.
    pub fn start_movement_phase(state: &mut GameState) -> Vec<GameEvent> {
        state.current_subphase = SubPhase::SelectUnitToMove;
        vec![GameEvent::PhaseStarted {
            phase: Phase::Movement,
            player: state.active_player,
        }]
    }

    /// Start the Shooting Phase.
    pub fn start_shooting_phase(state: &mut GameState) -> Vec<GameEvent> {
        state.current_subphase = SubPhase::SelectUnitToShoot;
        vec![GameEvent::PhaseStarted {
            phase: Phase::Shooting,
            player: state.active_player,
        }]
    }

    /// Start the Charge Phase.
    pub fn start_charge_phase(state: &mut GameState) -> Vec<GameEvent> {
        state.current_subphase = SubPhase::SelectUnitToCharge;
        vec![GameEvent::PhaseStarted {
            phase: Phase::Charge,
            player: state.active_player,
        }]
    }

    /// Start the Fight Phase.
    pub fn start_fight_phase(state: &mut GameState) -> Vec<GameEvent> {
        state.current_subphase = SubPhase::FightsFirst;
        vec![GameEvent::PhaseStarted {
            phase: Phase::Fight,
            player: state.active_player,
        }]
    }

    /// End the current player's turn and transition to the next player or round.
    ///
    /// If the first player just finished, start the second player's turn.
    /// If the second player just finished, end the battle round and check for game end.
    pub fn end_player_turn(state: &mut GameState) -> Vec<GameEvent> {
        let mut events = Vec::new();
        let current_player = state.active_player;

        events.push(GameEvent::TurnEnded {
            player: current_player,
            round: state.battle_round,
        });

        // Clear turn flags
        state.turn_flags.clear();
        state.player_mut(current_player).stratagem_usage.clear_turn();

        // Determine if this was the first or second player's turn
        let first_player = if state.players[0].first_turn {
            state.players[0].id
        } else {
            state.players[1].id
        };

        let second_player = if first_player == state.players[0].id {
            state.players[1].id
        } else {
            state.players[0].id
        };

        if current_player == first_player {
            // First player finished, start second player's turn
            state.active_player = second_player;
            state.decision_owner = second_player;
            state.current_phase = Phase::Command;
            state.current_subphase = SubPhase::CommandPhaseStart;

            events.push(GameEvent::TurnStarted {
                player: second_player,
                round: state.battle_round,
            });
            events.push(GameEvent::PhaseStarted {
                phase: Phase::Command,
                player: second_player,
            });
        } else {
            // Second player finished, end the battle round
            events.extend(Self::end_battle_round(state));
        }

        events
    }

    /// End the current battle round and check for game end.
    ///
    /// If 5 rounds have been completed, the game ends.
    /// Otherwise, advance to the next round and start the first player's turn.
    pub fn end_battle_round(state: &mut GameState) -> Vec<GameEvent> {
        let mut events = Vec::new();

        // Check for game end conditions
        if let Some(outcome) = Self::check_game_end(state) {
            state.game_outcome = outcome;
            state.current_phase = Phase::GameEnd;
            events.push(GameEvent::BattleEnded { outcome });
            return events;
        }

        // Advance to next round
        if let Some(next_round) = state.battle_round.next() {
            state.battle_round = next_round;

            // Clear faction round flags
            for player in &mut state.players {
                player.faction_round_flags.clear();
            }

            // Start first player's turn
            let first_player = if state.players[0].first_turn {
                state.players[0].id
            } else {
                state.players[1].id
            };

            state.active_player = first_player;
            state.decision_owner = first_player;
            state.current_phase = Phase::Command;
            state.current_subphase = SubPhase::CommandPhaseStart;

            events.push(GameEvent::BattleRoundStarted {
                round: state.battle_round,
            });
            events.push(GameEvent::TurnStarted {
                player: first_player,
                round: state.battle_round,
            });
            events.push(GameEvent::PhaseStarted {
                phase: Phase::Command,
                player: first_player,
            });
        } else {
            // Round 5 completed, game ends
            let outcome = Self::determine_winner(state);
            state.game_outcome = outcome;
            state.current_phase = Phase::GameEnd;
            events.push(GameEvent::BattleEnded { outcome });
        }

        events
    }

    /// Check if the game should end.
    ///
    /// The game ends when:
    /// 1. All 5 battle rounds are complete.
    /// 2. One player has been tabled (all units destroyed).
    ///
    /// Source: CP_Rules.md - "The battle lasts five battle rounds"
    pub fn check_game_end(state: &GameState) -> Option<GameOutcome> {
        // Check if either player is tabled
        let p0_tabled = state.is_player_tabled(state.players[0].id);
        let p1_tabled = state.is_player_tabled(state.players[1].id);

        if p0_tabled && p1_tabled {
            // Both tabled - determine by VP
            return Some(Self::determine_winner(state));
        }

        if p0_tabled {
            return Some(GameOutcome::Victory(state.players[1].id));
        }

        if p1_tabled {
            return Some(GameOutcome::Victory(state.players[0].id));
        }

        // Check if round 5 completed (checked in end_battle_round)
        None
    }

    /// Determine the winner based on VP.
    fn determine_winner(state: &GameState) -> GameOutcome {
        let vp0 = state.players[0].vp;
        let vp1 = state.players[1].vp;

        if vp0 > vp1 {
            GameOutcome::Victory(state.players[0].id)
        } else if vp1 > vp0 {
            GameOutcome::Victory(state.players[1].id)
        } else {
            GameOutcome::Draw
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::{GameState, PlayerState, TurnFlags};
    use wh40k_core_types::{
        ArmorSave, BaseSize, DatasheetId, KeywordSet, Leadership, MoveCharacteristic,
        ObjectiveControl, PlayerId, Toughness, UnitStatus, VictoryPoints, Wounds,
    };
    use wh40k_dice::{DiceContext, DiceRoller, StreamKind};
    use wh40k_event_system::EventBus;
    use wh40k_command_system::CommandHistory;
    use wh40k_geometry::Board;
    use crate::unit::{ModelState, UnitState};

    fn make_test_state() -> GameState {
        let seed = [42u8; 32];
        let ctx = DiceContext::new(seed, StreamKind::BattleShockTest, 0, 0);
        let dice_roller = DiceRoller::new(ctx);

        let mut state = GameState {
            content_version: "test-1.0".to_string(),
            scenario_id: None,
            battle_round: BattleRound::new(1),
            active_player: PlayerId::new(0),
            current_phase: Phase::PreBattle,
            current_subphase: SubPhase::DetermineAttackerDefender,
            decision_owner: PlayerId::new(0),
            players: [
                PlayerState::new(PlayerId::new(0), "Player A".to_string()),
                PlayerState::new(PlayerId::new(1), "Player B".to_string()),
            ],
            units: Vec::new(),
            board: Board::combat_patrol(),
            event_bus: EventBus::new(),
            command_history: CommandHistory::new(),
            dice_roller,
            active_effects: Vec::new(),
            reaction_windows: Vec::new(),
            turn_flags: TurnFlags::new(),
            game_outcome: GameOutcome::InProgress,
            deterministic_counter: 0,
        };

        // Player 0 goes first
        state.players[0].first_turn = true;

        state
    }

    fn make_test_unit_state(
        id: u32,
        owner: PlayerId,
        model_count: usize,
        wounds_per_model: u8,
    ) -> UnitState {
        let unit_id = wh40k_core_types::UnitId::new(id);
        let models: Vec<ModelState> = (0..model_count)
            .map(|i| {
                ModelState::new(
                    wh40k_core_types::ModelId::new(id * 100 + i as u32),
                    unit_id,
                    Wounds::new(wounds_per_model),
                    wh40k_core_types::Position::from_inches(10 + i as i32, 10),
                    BaseSize::MM32,
                    Vec::new(),
                    Vec::new(),
                    false,
                    None,
                )
            })
            .collect();

        let mut unit = UnitState::new(
            unit_id,
            owner,
            format!("Unit {}", id),
            DatasheetId::new(1),
            KeywordSet::from_keywords(&[wh40k_core_types::Keyword::Infantry]),
            models,
            MoveCharacteristic::from_inches(6),
            Toughness::new(4),
            ArmorSave::THREE_PLUS,
            None,
            Leadership::new(7),
            ObjectiveControl::new(2),
        );
        unit.status = UnitStatus::OnBattlefield;
        unit
    }

    #[test]
    fn test_advance_from_prebattle() {
        let mut state = make_test_state();
        let events = PhaseStateMachine::advance_phase(&mut state);

        assert_eq!(state.current_phase, Phase::Command);
        assert_eq!(state.current_subphase, SubPhase::CommandPhaseStart);
        assert_eq!(state.battle_round, BattleRound::new(1));

        // Should have BattleRoundStarted, TurnStarted, PhaseStarted
        assert!(events.iter().any(|e| matches!(e, GameEvent::BattleRoundStarted { .. })));
        assert!(events.iter().any(|e| matches!(e, GameEvent::TurnStarted { .. })));
        assert!(events.iter().any(|e| matches!(e, GameEvent::PhaseStarted { phase: Phase::Command, .. })));
    }

    #[test]
    fn test_advance_through_phases() {
        let mut state = make_test_state();
        state.current_phase = Phase::Command;
        state.current_subphase = SubPhase::CommandPhaseEnd;

        let events = PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Movement);
        assert!(events.iter().any(|e| matches!(e, GameEvent::PhaseEnded { phase: Phase::Command, .. })));
        assert!(events.iter().any(|e| matches!(e, GameEvent::PhaseStarted { phase: Phase::Movement, .. })));

        let events = PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Shooting);
        assert!(events.iter().any(|e| matches!(e, GameEvent::PhaseStarted { phase: Phase::Shooting, .. })));

        let events = PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Charge);
        assert!(events.iter().any(|e| matches!(e, GameEvent::PhaseStarted { phase: Phase::Charge, .. })));

        let events = PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Fight);
        assert!(events.iter().any(|e| matches!(e, GameEvent::PhaseStarted { phase: Phase::Fight, .. })));
    }

    #[test]
    fn test_end_first_player_turn() {
        let mut state = make_test_state();
        state.current_phase = Phase::Fight;
        state.active_player = PlayerId::new(0);
        state.players[0].first_turn = true;

        let events = PhaseStateMachine::advance_phase(&mut state);

        // Should transition to second player's command phase
        assert_eq!(state.active_player, PlayerId::new(1));
        assert_eq!(state.current_phase, Phase::Command);
        assert!(events.iter().any(|e| matches!(e, GameEvent::TurnEnded { player, .. } if *player == PlayerId::new(0))));
        assert!(events.iter().any(|e| matches!(e, GameEvent::TurnStarted { player, .. } if *player == PlayerId::new(1))));
    }

    #[test]
    fn test_end_second_player_turn_advances_round() {
        let mut state = make_test_state();
        state.current_phase = Phase::Fight;
        state.active_player = PlayerId::new(1);
        state.players[0].first_turn = true;
        state.battle_round = BattleRound::new(1);

        // Add units so nobody is tabled
        state.units.push(make_test_unit_state(1, PlayerId::new(0), 3, 2));
        state.units.push(make_test_unit_state(2, PlayerId::new(1), 3, 2));

        let events = PhaseStateMachine::advance_phase(&mut state);

        // Should advance to round 2
        assert_eq!(state.battle_round, BattleRound::new(2));
        assert_eq!(state.active_player, PlayerId::new(0)); // first player
        assert_eq!(state.current_phase, Phase::Command);
        assert!(events.iter().any(|e| matches!(e, GameEvent::BattleRoundStarted { round } if *round == BattleRound::new(2))));
    }

    #[test]
    fn test_game_ends_after_round_5() {
        let mut state = make_test_state();
        state.current_phase = Phase::Fight;
        state.active_player = PlayerId::new(1);
        state.players[0].first_turn = true;
        state.battle_round = BattleRound::new(5);

        // Add units so nobody is tabled
        state.units.push(make_test_unit_state(1, PlayerId::new(0), 3, 2));
        state.units.push(make_test_unit_state(2, PlayerId::new(1), 3, 2));

        // Give player 0 more VP
        state.players[0].vp = VictoryPoints::new(10);
        state.players[1].vp = VictoryPoints::new(5);

        let events = PhaseStateMachine::advance_phase(&mut state);

        assert_eq!(state.current_phase, Phase::GameEnd);
        assert_eq!(state.game_outcome, GameOutcome::Victory(PlayerId::new(0)));
        assert!(events.iter().any(|e| matches!(e, GameEvent::BattleEnded { .. })));
    }

    #[test]
    fn test_game_ends_draw() {
        let mut state = make_test_state();
        state.current_phase = Phase::Fight;
        state.active_player = PlayerId::new(1);
        state.players[0].first_turn = true;
        state.battle_round = BattleRound::new(5);

        state.units.push(make_test_unit_state(1, PlayerId::new(0), 3, 2));
        state.units.push(make_test_unit_state(2, PlayerId::new(1), 3, 2));

        state.players[0].vp = VictoryPoints::new(10);
        state.players[1].vp = VictoryPoints::new(10);

        let events = PhaseStateMachine::advance_phase(&mut state);

        assert_eq!(state.game_outcome, GameOutcome::Draw);
        assert!(events.iter().any(|e| matches!(e, GameEvent::BattleEnded { outcome: GameOutcome::Draw })));
    }

    #[test]
    fn test_tabling_ends_game() {
        let mut state = make_test_state();
        state.current_phase = Phase::Fight;
        state.active_player = PlayerId::new(1);
        state.players[0].first_turn = true;
        state.battle_round = BattleRound::new(2);

        // Player 0 has units, player 1 is tabled
        state.units.push(make_test_unit_state(1, PlayerId::new(0), 3, 2));
        let mut tabled_unit = make_test_unit_state(2, PlayerId::new(1), 3, 2);
        tabled_unit.status = UnitStatus::Destroyed;
        state.units.push(tabled_unit);

        let events = PhaseStateMachine::advance_phase(&mut state);

        assert_eq!(state.current_phase, Phase::GameEnd);
        assert_eq!(state.game_outcome, GameOutcome::Victory(PlayerId::new(0)));
        assert!(events.iter().any(|e| matches!(e, GameEvent::BattleEnded { .. })));
    }

    #[test]
    fn test_start_command_phase_gains_cp() {
        let mut state = make_test_state();
        state.current_phase = Phase::Command;
        state.current_subphase = SubPhase::CommandPhaseStart;

        assert_eq!(state.player(PlayerId::new(0)).cp.value(), 0);

        let events = PhaseStateMachine::start_command_phase(&mut state);

        assert_eq!(state.player(PlayerId::new(0)).cp.value(), 1);
        assert!(events.iter().any(|e| matches!(e, GameEvent::CommandPointsGained { amount: 1, .. })));
    }

    #[test]
    fn test_start_command_phase_battle_shock_check() {
        let mut state = make_test_state();
        state.current_phase = Phase::Command;

        // Add a unit that is below half strength
        let mut unit = make_test_unit_state(1, PlayerId::new(0), 6, 2);
        // Kill 5 of 6 models
        for i in 0..5 {
            unit.models[i].alive = false;
        }
        unit.update_below_half_strength();
        state.units.push(unit);

        let events = PhaseStateMachine::start_command_phase(&mut state);

        // Should emit a BattleShockTestRequired for the below-half-strength unit
        assert!(events.iter().any(|e| matches!(e, GameEvent::BattleShockTestRequired { .. })));
    }

    #[test]
    fn test_process_battle_shock() {
        let mut state = make_test_state();
        state.current_phase = Phase::Command;

        let unit = make_test_unit_state(1, PlayerId::new(0), 3, 2);
        let unit_id = unit.id;
        state.units.push(unit);

        let events = PhaseStateMachine::process_battle_shock(&mut state, unit_id);

        // Should have a BattleShockTestResolved event
        assert_eq!(events.len(), 1);
        match &events[0] {
            GameEvent::BattleShockTestResolved { unit, result, roll } => {
                assert_eq!(*unit, unit_id);
                // Based on the deterministic seed, verify the result is consistent
                match result {
                    BattleShockResult::Passed => {
                        assert!(!state.unit(unit_id).unwrap().battle_shocked);
                    }
                    BattleShockResult::Failed => {
                        assert!(state.unit(unit_id).unwrap().battle_shocked);
                    }
                }
                // Verify roll is a valid 2D6 result (2-12)
                assert!(*roll >= 2 && *roll <= 12);
            }
            _ => panic!("Expected BattleShockTestResolved"),
        }
    }

    #[test]
    fn test_full_round_progression() {
        let mut state = make_test_state();
        state.players[0].first_turn = true;

        // Add units so the game doesn't end from tabling
        state.units.push(make_test_unit_state(1, PlayerId::new(0), 3, 2));
        state.units.push(make_test_unit_state(2, PlayerId::new(1), 3, 2));

        // Start from PreBattle
        assert_eq!(state.current_phase, Phase::PreBattle);

        // PreBattle -> Command (Player 0)
        PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Command);
        assert_eq!(state.active_player, PlayerId::new(0));

        // Command -> Movement
        PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Movement);

        // Movement -> Shooting
        PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Shooting);

        // Shooting -> Charge
        PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Charge);

        // Charge -> Fight
        PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Fight);

        // Fight -> Command (Player 1's turn)
        PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.current_phase, Phase::Command);
        assert_eq!(state.active_player, PlayerId::new(1));

        // Player 1: Command -> Movement -> Shooting -> Charge -> Fight
        PhaseStateMachine::advance_phase(&mut state); // -> Movement
        assert_eq!(state.current_phase, Phase::Movement);

        PhaseStateMachine::advance_phase(&mut state); // -> Shooting
        assert_eq!(state.current_phase, Phase::Shooting);

        PhaseStateMachine::advance_phase(&mut state); // -> Charge
        assert_eq!(state.current_phase, Phase::Charge);

        PhaseStateMachine::advance_phase(&mut state); // -> Fight
        assert_eq!(state.current_phase, Phase::Fight);

        // End Player 1's turn -> Start Round 2, Player 0's turn
        PhaseStateMachine::advance_phase(&mut state);
        assert_eq!(state.battle_round, BattleRound::new(2));
        assert_eq!(state.active_player, PlayerId::new(0));
        assert_eq!(state.current_phase, Phase::Command);
    }

    #[test]
    fn test_phase_state_machine_game_end_no_advance() {
        let mut state = make_test_state();
        state.current_phase = Phase::GameEnd;
        state.game_outcome = GameOutcome::Draw;

        let events = PhaseStateMachine::advance_phase(&mut state);
        assert!(events.is_empty());
        assert_eq!(state.current_phase, Phase::GameEnd);
    }
}
